# Web server playbook
- name: Web server playbook
  hosts: vagrant
  become: yes
  become_user: root

  tasks:
    - name: install nginx
      apt:
        name: nginx
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
